@if ($activeTheme == 'multipurpose')
    @includeIf('front.multipurpose.partials.header')
@elseif($activeTheme == 'bakery')
    @includeIf('front.bakery.partials.header')
@elseif($activeTheme == 'pizza')
    @includeIf('front.pizza.partials.header')
@elseif($activeTheme == 'coffee')
    @includeIf('front.coffee.partials.header')
@elseif($activeTheme == 'medicine')
    @includeIf('front.medicine.partials.header')
@elseif($activeTheme == 'grocery')
    @includeIf('front.grocery.partials.header')
@elseif($activeTheme == 'beverage')
    @includeIf('front.beverage.partials.header')
@endif
